---
# tasks file for indexers


- name: add splunk user
  become: yes
  user:
   name: "{{ splunk_system_user }}"
   comment: "Splunk service user"
   createhome: yes
  tags:
   - createuser

- name: download installer for splunk
  command: "wget -O {{ main_installer_dest  }} {{ main_installer_url }} "
  tags:
   - downloadmainwget

- name: install Main splunk binary
  become: yes
  tags:
   - installmain
  unarchive:
    src: "{{ main_installer_dest  }}"
    dest: /opt/
    copy: no
    owner: "{{ splunk_system_user }}"
    group: "{{ splunk_system_user }}"
    creates: "{{ splunk_path }}/bin/splunk"

- name: accept splunk license on  indexers
  become: yes
  become_user: "{{ splunk_system_user }}"
  command: "{{ splunk_path  }}/bin/splunk start --accept-license --answer-yes"
  args:
   creates: "{{ splunk_path  }}/etc/users/splunk-system-user"
  environment:
   SPLUNK_HOME: "{{ splunk_path  }}"
  tags: start_splunk

- name: setup splunk to start at boot on indexers
  become: yes
  command: "{{ splunk_path  }}/bin/splunk enable boot-start -user splunk --accept-license --answer-yes"
  args:
   creates: "{{ splunk_path }}/etc/users/splunk-system-user"
  environment:
   SPLUNK_HOME: "{{ splunk_path  }}"
  tags: start_splunk_boot

- name:  change splunk admin password on indexers
  become: yes
  become_user: "{{ splunk_system_user }}"
  command: "{{ splunk_path  }}/bin/splunk edit user admin -auth {{ splunk_admin }}:{{ splunk_pass_old }} -password {{ splunk_pass  }}"
  environment:
   SPLUNK_HOME: "{{ splunk_path  }}"
  tags: set_password_in

- name: set default hostname and set servername idx1
  become: yes
  become_user: "{{ splunk_system_user }}"
  command: "{{ item }}"
  with_items:
  - "{{ splunk_path  }}/bin/splunk set servername  {{ indexer1_name }} -auth {{ splunk_admin }}:{{ splunk_pass }}"
  - "{{ splunk_path  }}/bin/splunk set default-hostname {{ indexer1_name }} -auth {{ splunk_admin }}:{{ splunk_pass }} "
  tags:
   - setsplunk-hostname_idx1

- name: set default hostname and set servername idx2
  become: yes
  become_user: "{{ splunk_system_user }}"
  command: 
  with_items:
  - "{{ splunk_path  }}/bin/splunk set servername {{ indexer2_name }} -auth {{ splunk_admin }}:{{ splunk_pass }} "
  - "{{ splunk_path  }}/bin/splunk set default-hostname  {{ indexer2_name }} -auth {{ splunk_admin }}:{{ splunk_pass }}"
  tags:
   - setsplunk-hostname_idx2


# - name: add search peers or indexers to searchhead
#   become: yes
#   become_user: "{{ splunk_system_user_root }}"
#   command: "{{ splunk_path  }}/bin/splunk add search-server https://{{ indexer_ip }}:8089 -auth admin:{{ splunk_pass }} -remoteUsername admin -remotePassword {{ splunk_pass }}"
#   environment:
#    SPLUNK_HOME: "{{ splunk_path  }}"
#   tags: add_indexer



# - name:  set deployment.conf from cli
#   become: yes
#   command: "{{ uf_path }}/bin/splunk set deploy-poll  {{ deployment_server_address }}:8089  -auth {{ splunk_admin }}:{{ splunk_pass  }}"
#   environment:
#    SPLUNK_HOME: "{{ uf_path }}"
#   tags:
#    - configure_uf_d_cli


- name: stop splunk service
  become: yes
  command: "{{ splunk_path  }}/bin/splunk stop"
  environment:
   SPLUNK_HOME: "{{ splunk_path  }}"
  tags: stop_splunk
