---
# tasks file for indexers


- name: add splunk user
  become: yes
  user:
   name: "{{ splunk_system_user }}"
   comment: "Splunk service user"
   createhome: yes
  tags:
   - createuser
     
- name: set idx1 system hostname
  become: yes
  hostname:
    name: idx1
  tags:
    - set_idx1_hostname
    
- name: set idx2 system hostname
  become: yes
  hostname:
    name: idx2
  tags:
    - set_idx2_hostname

- name: download installer for splunk
  command: "wget -O {{ main_installer_dest  }} {{ main_installer_url }} "
  tags:
   - downloadmainwget

- name: install Main splunk binary
  become: yes
  tags:
   - installmain
  unarchive:
    src: "{{ main_installer_dest  }}"
    dest: /opt/
    copy: no
    owner: "{{ splunk_system_user }}"
    group: "{{ splunk_system_user }}"
    creates: "{{ splunk_path }}/bin/splunk"

- name: accept splunk license on  indexers
  become: yes
  become_user: "{{ splunk_system_user }}"
  command: "{{ splunk_path  }}/bin/splunk start --accept-license --answer-yes"
  args:
   creates: "{{ splunk_path  }}/etc/users/splunk-system-user"
  environment:
   SPLUNK_HOME: "{{ splunk_path  }}"
  tags: start_splunk

- name: setup splunk to start at boot on indexers
  become: yes
  command: "{{ splunk_path  }}/bin/splunk enable boot-start -user splunk --accept-license --answer-yes"
  args:
   creates: "{{ splunk_path }}/etc/users/splunk-system-user"
  environment:
   SPLUNK_HOME: "{{ splunk_path  }}"
  tags: start_splunk_boot

- name:  change splunk admin password on indexers
  become: yes
  become_user: "{{ splunk_system_user }}"
  command: "{{ splunk_path  }}/bin/splunk edit user admin -auth {{ splunk_admin }}:{{ splunk_pass_old }} -password {{ splunk_pass  }}"
  environment:
   SPLUNK_HOME: "{{ splunk_path  }}"
  tags: set_password_in
  ignore_errors: yes

- name: set default hostname and set servername idx1
  become: yes
  become_user: "{{ splunk_system_user }}"
  command: "{{ item }}"
  with_items:
  - "{{ splunk_path  }}/bin/splunk set servername  {{ indexer1_name }} -auth {{ splunk_admin }}:{{ splunk_pass }}"
  - "{{ splunk_path  }}/bin/splunk set default-hostname {{ indexer1_name }} -auth {{ splunk_admin }}:{{ splunk_pass }} "
  tags:
   - setsplunk-hostname_idx1
  notify: restart splunk

- name: set default hostname and set servername idx2
  become: yes
  become_user: "{{ splunk_system_user }}"
  command: "{{ item }}"
  with_items:
  - "{{ splunk_path  }}/bin/splunk set servername {{ indexer2_name }} -auth {{ splunk_admin }}:{{ splunk_pass }} "
  - "{{ splunk_path  }}/bin/splunk set default-hostname  {{ indexer2_name }} -auth {{ splunk_admin }}:{{ splunk_pass }}"
  tags:
   - setsplunk-hostname_idx2
  notify: restart splunk
  
- name:  set deployment.conf from cli
  become: yes
  become_user: "{{ splunk_system_user }}"
  command: "{{ splunk_path }}/bin/splunk set deploy-poll  {{ deployment_server_address }}:8089  -auth {{ splunk_admin }}:{{ splunk_pass  }}"
  environment:
   SPLUNK_HOME: "{{ splunk_path }}"
  tags:
   - configure_idx_d_cli
  notify: restart splunk
  
  
- name:  show deployment.conf status from cli
  become: yes
  become_user: "{{ splunk_system_user }}"
  command: "{{ splunk_path }}/bin/splunk show deploy-poll  -auth {{ splunk_admin }}:{{ splunk_pass  }}"
  environment:
   SPLUNK_HOME: "{{ splunk_path }}"
  tags:
   - configure_idx_d_cli
   
- name:  set indexers to listen to forwarders on port 9997
  become: yes
  become_user: "{{ splunk_system_user }}"
  command: "{{ splunk_path }}/bin/splunk enable listen  9997  -auth {{ splunk_admin }}:{{ splunk_pass  }}"
  environment:
   SPLUNK_HOME: "{{ splunk_path }}"
  tags:
   - configure_idx_d_cli
  notify: restart splunk
  ignore_errors: yes
  
- name:  show indexers to listening status or port
  become: yes
  become_user: "{{ splunk_system_user }}"
  command: "{{ splunk_path }}/bin/splunk display listen -auth {{ splunk_admin }}:{{ splunk_pass  }}"
  environment:
   SPLUNK_HOME: "{{ splunk_path }}"
  tags:
   - show_idx_d_cli 
  
  
- name: create frozen dir on idxs
  become: yes
  file:
    path: "/opt/frozen"
    state: directory
    owner: "{{ splunk_system_user }}"
    group: "{{ splunk_system_user }}"
    mode: 0755
  tags:
   - create_idxs_frozen_dir
  
- name:  create diag on idxs
  become: yes
  become_user: "{{ splunk_system_user }}"
  command: "{{ splunk_path }}/bin/splunk diag "
  tags:
   - run_diag

- name:   stat file idxs
  shell: "ls -d {{ splunk_path }}/diag*"
  register: diag_file_name
  tags:
   - run_diag2
   
- name: change file mode idxs
  become: yes
  become_user: "{{ splunk_system_user }}"
  file:
    path: "{{ diag_file_name.stdout }}"
    mode: 0755
  tags:
   - run_diag2
 
- name:  mv diag on idxs
  become: yes
  become_user: "{{ splunklab_user }}"
  command:  "cp {{ diag_file_name.stdout }}   /home/{{ splunklab_user }}/SOYINKA-Indexer.tar.gz"
  tags:
   - run_diag2
